# Generated by Django 5.2.12 on 2026-06-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_sitestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedhistory',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='scannedhistory',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='scannedhistory',
            unique_together={('session_key', 'url')},
        ),
    ]
