# Generated by Django 5.2.12 on 2026-06-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_scannedhistory_session_key_alter_scannedhistory_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitestats',
            name='total_visitors',
            field=models.PositiveIntegerField(default=290),
        ),
    ]
